on:
  # Trigger the workflow on push or pull request, but only for the develop branch
  push:
    branches:
      - '*'

jobs:
  test_macos:
    runs-on: macos-11
    env:
      # a fixed path is required to use precompiled dependencies
      WRK_DIR: /Users/Shared/work

    name: Python 3.x on macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      # Install the latest version of the same dependencies that are used to
      # create the app. Determine the canoncial path and store it in VER_DIR
      # (e.g. "/Users/Shared/work/jhb-0.4"). Run a reconfiguration to adapt
      # to the system this is running on (path to MacOSX.sdk).
      - name: Install dependencies
        id: dependencies
        run: |
          ARCH=$(uname -m)
          mkdir $WRK_DIR
          curl -L https://gitlab.com/dehesselle/zim_macos/-/jobs/artifacts/master/raw/jhb-zim_$ARCH.tar.xz?job=build_zim:$ARCH | tar -C $WRK_DIR -xpJ
          VER_DIR=$(echo $WRK_DIR/jhb-*)
          echo "::set-output name=VER_DIR::$VER_DIR"
          source $VER_DIR/etc/jhb.conf.sh
          source $VER_DIR/usr/src/jhb/jhbuild.sh
          jhbuild_configure

      # Remove GraphViz ("dot") to skip testing "Diagram Editor" plugin (that
      # test isn't run on any other platform and appears to be broken) and
      # run the test suite.
      - name: Test macOS
        run: |
          rm $VER_DIR/bin/dot
          $VER_DIR/usr/bin/jhb run python3 $(pwd)/test.py
        env:
          VER_DIR: ${{ steps.dependencies.outputs.VER_DIR }}
          SYS_IGNORE_USR_LOCAL: true

